class AppRoutes {
  static const String splashPageRoute = "/SplashScreen"; //FirstPage
  static const String onBoardingRoute = "OnBoardingScreen";
  static const String registerRoute = "RegisterScreen";
  static const String loginRoute = "LoginScreen";
  static const String interestedWorkRoute = "InterestedWork";
  static const String locationRoute = "Location";
  static const String accountSetupRoute = "AccountSetup";
  static const String restPasswordRoute = "RestPassword";
  static const String checkEmailRoute = "CheckEmail";
  static const String createNewPasswordRoute = "CreateNewPassword";
  static const String passwordSuccessfullyRoute = "PasswordChangedSuccessfully";
  static const String bottomNavigationRoute = "BottomNavigation";
  static const String searchScreenRoute = "SearchScreen";
  static const String filterSearchRoute = "FilterSearch";
  static const recentJobCardRoute = "RecentJobCard";
  static const String notificationScreenRoute = "NotificationScreen";
  static const String archiveMessagesRoute = "ArchiveMessages";
  static const String unReadMessagesRoute = "UnReadMessages";
  static const String spamMessagesRoute = "SpamMessages";
  static const String chatScreenRoute = "ChatScreen";
  static const String jobDetailsRoute = "JobDetails";
  static const String savedScreenRoute = "SavedScreen";
  static const String applyJobScreenRoute = "ApplyJobScreen";
  static const String editeProfilePageRoute = "EditeProfilePage";
  static const String stepperAppliedJobRoute = "StepperAppliedJob";
  static const String completeProfileRoute = "CompleteProfile";
  static const String portfolioRoute = "PortfolioScreen";
  static const String notificationProfileRoute =
      "NotificationProfileScreen";
  static const String loginAndSecurityRoute = "LoginAndSecurityScreen";
  static const String emailAddressProfileRoute = "EmailAddressProfile";
  static const String experienceRoute = "ExperienceScreen";
  static const String educationRoute = "EducationScreen";
  static const String personalDetailsRoute = "PersonalDetailsScreen";
  static const String phoneNumberProfileRoute = "PhoneNumberProfile";
  static const String changePasswordProfileRoute = "ChangePasswordProfile";
  static const String twoStepVerificationRoute = "TwoStepVerification";
  static const String helpCenterRoute = "HelpCenterScreen";
  static const String termsConditionsRoute = "TermsConditionsScreen";
  static const String privacyPolicyRoute = "PrivacyPolicyScreen";
  static const String languageRoute = "LanguageScreen";
  static const String phoneTwoStepRoute = "PhoneTwoStep";
  static const String otpRoute = "OtpScreen";
// static const String Route= "";
// static const String Route= "";
// static const String Route= "";
// static const String Route= "";
// static const String Route= "";

}
